### PR TITLE
Development

### PR DESCRIPTION
**Pull request by mosesogwo**
Awaiting TSE review.

### CODE REVIEW

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
Hello @mosesogwo @keshav-c , Great Work :) 

Everything looks good so far but it will be better if you can make few small changes.

- Navigation items is not vertically in the middle- make it so .

- Latest news section  is very congested when in mobile screen-please make some room and give them space, also use different images in this section  it will make it look better.

- You can put your css reset in the main.css file- do not need any extra file.

Please submit for another review after making those changes.

Happy Coding

**Comment by keshav-c** [comment]
Thanks @AdnanAfsari for your timely review. Could you elaborate on what exactly is required to be done regarding, the navigation items not being vertically in the middle? 

If you mean for the menu button to be functional, that requires javascript and this project is for us to execute with CSS/HTML alone.

**Comment by AdnanAfsari** [comment]
Hello @mosesogwo @keshav-c 

if you check the original navigation item its actually vertically in the middle, have a look
Screenshot 2019-05-25 at 12 34 06 AM

but your navigation items are slightly above then middle 
Screenshot 2019-05-25 at 12 33 51 AM copy

so you have to tweak your css a little bit to make it so.

please fix the issue and submit for final review 

Happy Coding :)

**Comment by mosesogwo** [comment]
Thanks @AdnanAfsari 
We have vertically centered the nav items.

**Comment by AdnanAfsari** [comment]
Hello @mosesogwo @keshav-c , Congratulation 👍 

Great work you can go ahead and merge the branch :)

Happy Coding

**Pull request merged**
